FHIR Diagnostic Resource, Profile, Mapping, Example resource
openmrs/openmrs-contrib-fhir2-ig pull request #30
Opened 2022-08-01 21:15 UTC by sherrif10

https://issues.openmrs.org/browse/FM2-502

2022-09-20 21:27 UTC, pmanko requested changes
Looks good, but I'm not sure about the identifier for the DiagnosticReport. Other fields also don't seem to be supported in the fhir2 module - for example `resultsInterpreter` and `imagingStudy`. In this IG we should only list the fields that our module supports.

2022-09-20 21:27 UTC, pmanko commented on input/fsh/omrs-diagnosticReport.fsh
> +* identifier.id = "53fbd0ef-ae10-46a0-9d0a-387917a66d6e"
Does the FHIR2 module translate into a diagnostic report with an identifier? I don't see it anywhere in the translator: https://github.com/openmrs/openmrs-module-fhir2/blob/master/api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/DiagnosticReportTranslatorImpl.java

2022-09-20 21:27 UTC, pmanko commented on input/fsh/omrs-diagnosticReport.fsh
> +* identifier.id = "53fbd0ef-ae10-46a0-9d0a-387917a66d6e"
I also don't see any identifiers in the example DR from the fhir2 tests: https://github.com/openmrs/openmrs-module-fhir2/blob/master/test-data/src/test/resources/org/openmrs/module/fhir2/providers/DiagnosticReport_create_r4.json

2022-09-22 18:59 UTC, sherrif10 commented
cc @pmanko . Looking forward for your reviews.

2022-10-08 01:59 UTC, merged