FM2-512: FHIR IG Observation Resource Example
openmrs/openmrs-contrib-fhir2-ig pull request #38
Opened 2022-09-09 20:57 UTC by abertnamanya

Issue Ticket: https://issues.openmrs.org/browse/FM2-512

![Screenshot from 2022-09-09 23-56-51](https://user-images.githubusercontent.com/19745793/189443910-b9b66e15-192a-4889-91f4-1f59f0f3edaf.png)

![Screenshot from 2022-09-09 23-56-37](https://user-images.githubusercontent.com/19745793/189443927-c1cc8860-aadb-453a-a657-a4823217217a.png)

2022-09-20 21:10 UTC, pmanko approved these changes

2022-09-20 21:56 UTC, pmanko requested changes
double-check that all defined fields are being mapped in the translator: https://github.com/openmrs/openmrs-module-fhir2/blob/master/api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java

2022-09-20 21:56 UTC, pmanko commented on input/fsh/omrs-observation.fsh
>  * identifier.value = "e8f8d71a-6c14-4105-b6fe-30f3cf6b7dc9"
I don't think we map an identifier field in the translator: https://github.com/openmrs/openmrs-module-fhir2/blob/master/api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java

2022-10-08 02:07 UTC, pmanko approved these changes

2022-10-10 22:00 UTC, abertnamanya commented
@pmanko  I think I have messed up the code by trying to resolve the conflict in the PR, even other commits of different branches are coming in.

2022-12-05 07:08 UTC, abertnamanya commented
@pmanko How can I resolved the issue of combining multiple commits

2023-03-15 20:26 UTC, merged